/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.imam.sp_checklist;

/**
 *
 * @author Imam-pc
 */
public class Welcome extends javax.swing.JPanel {

    /**
     * Creates new form Welcomee
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonImageReflection2 = new usu.widget.glass.ButtonImageReflection();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        buttonImageReflection2.setForeground(new java.awt.Color(0, 0, 0));
        buttonImageReflection2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imam/sp_checklist/image/secure-welcome.jpg"))); // NOI18N
        buttonImageReflection2.setText("        SISTEM APLIKASI PENDATAAN PARKIR KENDARAAN");
        buttonImageReflection2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        buttonImageReflection2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(buttonImageReflection2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.ButtonImageReflection buttonImageReflection2;
    // End of variables declaration//GEN-END:variables
}
