/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.imam.sp_checklist.view.laporan;

import com.imam.sp_checklist.entity.master.Karyawan;
import com.imam.sp_checklist.entity.master.Shift;
import com.imam.sp_checklist.manager.ManageDataKaryawan;
import com.imam.sp_checklist.manager.ManageDataShift;
import com.imam.sp_checklist.manager.SpringManager;
import com.imam.sp_checklist.widget.ProgressbarLoading;
import java.awt.Window;
import java.beans.PropertyChangeEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormatSymbols;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.SessionFactory;
import org.hibernate.classic.Session;
import org.hibernate.jdbc.Work;

/**
 *
 * @author Imam-pc
 */
public class LaporanTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form LaporanMaster
     */
    
    private Locale locale = Locale.forLanguageTag("in-ID");
    
    public LaporanTransaksi() {
        initComponents();
    }
    
    public void LoadComboPengawas(){
        List<Karyawan> kr = ManageDataKaryawan.getInstance().getKaryawanPengawas();
        comboPengawasJadwal.removeAllItems();
        comboPengawasCeklis.removeAllItems();
        comboPengawasJadwal.addItem("All");
        comboPengawasCeklis.addItem("All");
        kr.stream().map((akses) -> {
            comboPengawasJadwal.addItem(akses);
            return akses;
        }).forEachOrdered((akses) -> {
            comboPengawasCeklis.addItem(akses);
        });
        
    }
    
    public void LoadComboPetugas(){
        List<Karyawan> kr = ManageDataKaryawan.getInstance().getKaryawanPetugas();

        comboPetugasCeklis.removeAllItems();
        comboPetugasJadwal.removeAllItems();
        comboPetugasCeklis.addItem("All");
        comboPetugasJadwal.addItem("All");
        kr.stream().map((akses) -> {
            comboPetugasJadwal.addItem(akses);
            return akses;
        }).forEachOrdered((akses) -> {
            comboPetugasCeklis.addItem(akses);
        });
        
    }
    
    public void LoadComboShift(){
        List<Shift> shifts = ManageDataShift.getInstance().getShiftAll();
        comboShift.removeAllItems();
        comboShift.addItem("All");
        shifts.forEach((akses) -> {
            comboShift.addItem(akses);
        });
        
    }
    
    public JasperPrint displayReport(Map<String,Object>param,String varParam, Connection koneksi){
        JasperPrint jasperPrint = null;
        try {
            
            
                InputStream inputStream = getClass().getResourceAsStream(varParam);
                jasperPrint = JasperFillManager.fillReport(inputStream, param, koneksi);
                JasperViewer.viewReport(jasperPrint,false);
            
            
        } catch (JRException ex) {
            Logger.getLogger(LaporanMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
        return jasperPrint;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnLapJadwal = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        blnCuserJadwal = new com.toedter.calendar.JMonthChooser();
        thnCuserJadwal = new com.toedter.calendar.JYearChooser();
        comboPengawasJadwal = new javax.swing.JComboBox();
        comboPetugasJadwal = new javax.swing.JComboBox();
        rbAllJadwal = new javax.swing.JRadioButton();
        rbBlnJadwal = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnLapCeklis = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rbAllCeklisTgl = new javax.swing.JRadioButton();
        rbTgl = new javax.swing.JRadioButton();
        dateCeklisSampai = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        dateCeklisDari = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        comboShift = new javax.swing.JComboBox();
        comboPengawasCeklis = new javax.swing.JComboBox();
        comboPetugasCeklis = new javax.swing.JComboBox();
        rbAllCeklisBln = new javax.swing.JRadioButton();
        rbBlnCeklis = new javax.swing.JRadioButton();
        blnCuserCeklis = new com.toedter.calendar.JMonthChooser();
        thnCuserCeklis = new com.toedter.calendar.JYearChooser();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Laporan Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 18))); // NOI18N
        setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Laporan Jadwal Petugas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel10.setText("Petugas");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setText(":");

        btnLapJadwal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnLapJadwal.setText("Tampilkan Laporan");
        btnLapJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapJadwalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel13.setText("Pengawas");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel14.setText(":");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel15.setText("Bln / Thn");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel16.setText(":");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel17.setText("Status");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel18.setText(":");

        comboStatus.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Selesai", "Belum Selesai" }));

        blnCuserJadwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        blnCuserJadwal.setEnabled(false);
        blnCuserJadwal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        thnCuserJadwal.setEnabled(false);

        comboPengawasJadwal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboPengawasJadwal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));

        comboPetugasJadwal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboPetugasJadwal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));

        buttonGroup2.add(rbAllJadwal);
        rbAllJadwal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbAllJadwal.setText("All");
        rbAllJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAllJadwalActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbBlnJadwal);
        rbBlnJadwal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbBlnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlnJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnLapJadwal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAllJadwal)
                                .addGap(18, 18, 18)
                                .addComponent(rbBlnJadwal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blnCuserJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thnCuserJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPengawasJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPetugasJadwal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(96, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(comboPengawasJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(comboPetugasJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbBlnJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(rbAllJadwal))
                    .addComponent(blnCuserJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thnCuserJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnLapJadwal)
                .addGap(34, 34, 34))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Laporan Checklist Kendaraan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel11.setText("Petugas");

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel19.setText(":");

        btnLapCeklis.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnLapCeklis.setText("Tampilkan Laporan");
        btnLapCeklis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapCeklisActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel20.setText("Pengawas");

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel21.setText(":");

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel22.setText("Bln / Thn");

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel23.setText(":");

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel24.setText("Tgl Checklist");

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel25.setText(":");

        buttonGroup1.add(rbAllCeklisTgl);
        rbAllCeklisTgl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbAllCeklisTgl.setSelected(true);
        rbAllCeklisTgl.setText("All");
        rbAllCeklisTgl.setOpaque(false);
        rbAllCeklisTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAllCeklisTglActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTgl);
        rbTgl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbTgl.setOpaque(false);
        rbTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTglActionPerformed(evt);
            }
        });

        dateCeklisSampai.setDate(new java.util.Date());
        dateCeklisSampai.setDateFormatString("EEEE, d MMMM yyyy");
        dateCeklisSampai.setEnabled(false);
        dateCeklisSampai.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel26.setText("Shift");

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel27.setText(":");

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel28.setText("Dari");

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel29.setText("Sampai");

        dateCeklisDari.setDate(new java.util.Date());
        dateCeklisDari.setDateFormatString("EEEE, d MMMM yyyy");
        dateCeklisDari.setEnabled(false);
        dateCeklisDari.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel30.setText(":");

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel31.setText(":");

        comboShift.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));

        comboPengawasCeklis.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboPengawasCeklis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));

        comboPetugasCeklis.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboPetugasCeklis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));

        buttonGroup3.add(rbAllCeklisBln);
        rbAllCeklisBln.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbAllCeklisBln.setSelected(true);
        rbAllCeklisBln.setText("All");
        rbAllCeklisBln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAllCeklisBlnActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbBlnCeklis);
        rbBlnCeklis.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbBlnCeklis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlnCeklisActionPerformed(evt);
            }
        });

        blnCuserCeklis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        blnCuserCeklis.setEnabled(false);
        blnCuserCeklis.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        thnCuserCeklis.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAllCeklisTgl)
                                .addGap(18, 18, 18)
                                .addComponent(rbTgl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateCeklisSampai, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(dateCeklisDari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnLapCeklis))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboShift, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboPetugasCeklis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboPengawasCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAllCeklisBln)
                                .addGap(18, 18, 18)
                                .addComponent(rbBlnCeklis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blnCuserCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thnCuserCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(comboPengawasCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19)
                    .addComponent(comboPetugasCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23))
                    .addComponent(rbBlnCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbAllCeklisBln)
                    .addComponent(blnCuserCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thnCuserCeklis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(rbAllCeklisTgl))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30))
                            .addComponent(dateCeklisDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateCeklisSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(comboShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLapCeklis)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapJadwalActionPerformed
        // TODO add your handling code here:
        
        SessionFactory sessionFactory = SpringManager.getInstance().getBean(SessionFactory.class);
            Session session = sessionFactory.openSession();
            
            session.doWork(new Work() {

                @Override
                public void execute(Connection connection) throws SQLException {
                    String inputStream = "/com/imam/sp_checklist/report/LapTransaksiJadwal.jasper";
                    String varPgn = comboPengawasJadwal.getSelectedItem().toString();
                    String varPns = comboPetugasJadwal.getSelectedItem().toString();
                    String[] splitPgn;
                    String[] splitPns;
                    String varSplitPgn;
                    String varSplitGrup;
                    if(varPgn.equals("All")){
                        varSplitPgn = "";
                    }else{
                        splitPgn = varPgn.split("-");
                        System.out.println("Split Pengawas jadwal: "+Arrays.toString(splitPgn));
                        varSplitPgn = splitPgn[0];
                        System.out.println("Split Pengawas jadwal string: "+varSplitPgn);
                    }
                    if(varPns.equals("All")){
                        varSplitGrup = "";
                    }else{
                        splitPns = varPns.split("-");
                        System.out.println("Split Petugas jadwal: "+Arrays.toString(splitPns));
                        varSplitGrup = splitPns[0];
                        System.out.println("Split Petugas jadwal string: "+varSplitGrup);
                    }
                    String flag;
                    switch (comboStatus.getSelectedIndex()) {
                        case 0:
                            flag = "true,false";
                            break;
                        case 1:
                            flag = "true";
                            break;
                        default:
                            flag = "false";
                            break;
                    }
                    String bulan;
                    int[] tahun;
                    if(rbAllJadwal.isSelected()==true){
                        
                        bulan = "";
                        tahun = new int[]{};
                    }else{
                        
                        int month = blnCuserJadwal.getMonth();
                        DateFormatSymbols dfs = new DateFormatSymbols(locale);
                        String namaBln = dfs.getMonths()[month];
                        System.out.println("Bulan String: "+namaBln);
                        
                        bulan = namaBln;
                        tahun = new int[]{thnCuserJadwal.getYear()};
                        
                    }
                    Map<String, Object> map = new HashMap<>();
                    map.put("pengawas", varSplitPgn);
                    map.put("petugas", varSplitGrup);
                    map.put("bulan", bulan);
                    map.put("thn", tahun);
                    map.put("status", flag);
                    map.put(JRParameter.REPORT_CONNECTION, connection);
                    map.put(JRParameter.REPORT_LOCALE, new Locale("in", "ID"));
                    final SwingWorker<JasperPrint, String> worker = new SwingWorker<JasperPrint, String>(){
                        
                        @Override
                        protected JasperPrint doInBackground() throws Exception {
                            JasperPrint print;
                            print = displayReport(map, inputStream, connection);
                            
                            return print;
                        }
                        
                    };
                    Window win = SwingUtilities.getWindowAncestor((AbstractButton)evt.getSource());
                    ProgressbarLoading loding = new ProgressbarLoading();
                    worker.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
                        if (evt1.getPropertyName().equals("state")) {
                            if (evt1.getNewValue() == SwingWorker.StateValue.DONE) {
                                loding.dispose();
                            }
                        }
                    });
                    worker.execute();
                    loding.pack();
                    loding.setLocationRelativeTo(win);
                    loding.setVisible(true);
                }
            });
            session.close();
        
    }//GEN-LAST:event_btnLapJadwalActionPerformed

    private void rbAllJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAllJadwalActionPerformed
        // TODO add your handling code here:
        
        if(rbAllJadwal.isSelected()==true){
            blnCuserJadwal.setEnabled(false);
            thnCuserJadwal.setEnabled(false);
        }else{
            blnCuserJadwal.setEnabled(true);
            thnCuserJadwal.setEnabled(true);
        }
        
    }//GEN-LAST:event_rbAllJadwalActionPerformed

    private void rbBlnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlnJadwalActionPerformed
        // TODO add your handling code here:
        if(rbBlnJadwal.isSelected()==true){
            blnCuserJadwal.setEnabled(true);
            thnCuserJadwal.setEnabled(true);
        }else{
            blnCuserJadwal.setEnabled(false);
            thnCuserJadwal.setEnabled(false);
        }
    }//GEN-LAST:event_rbBlnJadwalActionPerformed

    private void btnLapCeklisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapCeklisActionPerformed
        // TODO add your handling code here:
        
        SessionFactory sessionFactory = SpringManager.getInstance().getBean(SessionFactory.class);
            Session session = sessionFactory.openSession();
            
            session.doWork(new Work() {

                @Override
                public void execute(Connection connection) throws SQLException {
                    String inputStream;
                    String varPgn = comboPengawasCeklis.getSelectedItem().toString();
                    String varPns = comboPetugasCeklis.getSelectedItem().toString();
                    String[] splitPgn;
                    String[] splitPns;
                    String varSplitPgn;
                    String varSplitGrup;
                    if(varPgn.equals("All")){
                        varSplitPgn = "";
                    }else{
                        splitPgn = varPgn.split("-");
                        System.out.println("Split Pengawas jadwal: "+Arrays.toString(splitPgn));
                        varSplitPgn = splitPgn[0];
                        System.out.println("Split Pengawas jadwal string: "+varSplitPgn);
                    }
                    if(varPns.equals("All")){
                        varSplitGrup = "";
                    }else{
                        splitPns = varPns.split("-");
                        System.out.println("Split Petugas jadwal: "+Arrays.toString(splitPns));
                        varSplitGrup = splitPns[0];
                        System.out.println("Split Petugas jadwal string: "+varSplitGrup);
                    }
                    String bulan;
                    int[] tahun;
                    if(rbAllJadwal.isSelected()==true){
                        
                        bulan = "";
                        tahun = new int[]{};
                    }else{
                        
                        int month = blnCuserJadwal.getMonth();
                        DateFormatSymbols dfs = new DateFormatSymbols(locale);
                        String namaBln = dfs.getMonths()[month];
                        System.out.println("Bulan String: "+namaBln);
                        
                        bulan = namaBln;
                        tahun = new int[]{thnCuserJadwal.getYear()};
                        
                    }
                    String sip;
                    if(comboShift.getSelectedIndex() == 0){
                        sip = "";
                    }else{
                        sip = comboShift.getSelectedItem().toString();
                    }
                    Map<String, Object> map = new HashMap<>();
                    map.put("pengawas", varSplitPgn);
                    map.put("petugas", varSplitGrup);
                    map.put("bulan", bulan);
                    map.put("thn", tahun);
                    map.put("shift", sip);
                    if(rbAllCeklisTgl.isSelected()==true){
                        inputStream = "/com/imam/sp_checklist/report/LapTransaksiCeklis.jasper";
                    }else{
                        inputStream = "/com/imam/sp_checklist/report/LapTransaksiCeklisTgl.jasper";
                        
                        map.put("tglFrom", new java.sql.Date(dateCeklisDari.getDate().getTime()));
                        map.put("tglTo", new java.sql.Date(dateCeklisSampai.getDate().getTime()));
                    }
                    map.put(JRParameter.REPORT_CONNECTION, connection);
                    map.put(JRParameter.REPORT_LOCALE, new Locale("in", "ID"));
                    final SwingWorker<JasperPrint, String> worker = new SwingWorker<JasperPrint, String>(){
                        
                        @Override
                        protected JasperPrint doInBackground() throws Exception {
                            JasperPrint print;
                            print = displayReport(map, inputStream, connection);
                            
                            return print;
                        }
                        
                    };
                    Window win = SwingUtilities.getWindowAncestor((AbstractButton)evt.getSource());
                    ProgressbarLoading loding = new ProgressbarLoading();
                    worker.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
                        if (evt1.getPropertyName().equals("state")) {
                            if (evt1.getNewValue() == SwingWorker.StateValue.DONE) {
                                loding.dispose();
                            }
                        }
                    });
                    worker.execute();
                    loding.pack();
                    loding.setLocationRelativeTo(win);
                    loding.setVisible(true);
                }
            });
            session.close();
        
    }//GEN-LAST:event_btnLapCeklisActionPerformed

    private void rbAllCeklisBlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAllCeklisBlnActionPerformed
        // TODO add your handling code here:
        
        if(rbAllCeklisBln.isSelected()==true){
            blnCuserCeklis.setEnabled(false);
            thnCuserCeklis.setEnabled(false);
        }else{
            blnCuserCeklis.setEnabled(true);
            thnCuserCeklis.setEnabled(true);
        }
        
    }//GEN-LAST:event_rbAllCeklisBlnActionPerformed

    private void rbBlnCeklisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlnCeklisActionPerformed
        // TODO add your handling code here:
        if(rbBlnCeklis.isSelected()==true){
            blnCuserCeklis.setEnabled(true);
            thnCuserCeklis.setEnabled(true);
        }else{
            blnCuserCeklis.setEnabled(false);
            thnCuserCeklis.setEnabled(false);
        }
    }//GEN-LAST:event_rbBlnCeklisActionPerformed

    private void rbAllCeklisTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAllCeklisTglActionPerformed
        // TODO add your handling code here:
        
        if(rbAllCeklisTgl.isSelected()==true){
            dateCeklisDari.setEnabled(false);
            dateCeklisSampai.setEnabled(false);
            dateCeklisDari.setDate(null);
            dateCeklisSampai.setDate(null);
        }else{
            dateCeklisDari.setEnabled(true);
            dateCeklisSampai.setEnabled(true);
            dateCeklisDari.setDate(new java.util.Date());
            dateCeklisSampai.setDate(new java.util.Date());
        }
        
    }//GEN-LAST:event_rbAllCeklisTglActionPerformed

    private void rbTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTglActionPerformed
        // TODO add your handling code here:
        
        if(rbTgl.isSelected()==true){
            dateCeklisDari.setEnabled(true);
            dateCeklisSampai.setEnabled(true);
            dateCeklisDari.setDate(new java.util.Date());
            dateCeklisSampai.setDate(new java.util.Date());
        }else{
            dateCeklisDari.setEnabled(false);
            dateCeklisSampai.setEnabled(false);
            dateCeklisDari.setDate(null);
            dateCeklisSampai.setDate(null);
        }
        
    }//GEN-LAST:event_rbTglActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JMonthChooser blnCuserCeklis;
    private com.toedter.calendar.JMonthChooser blnCuserJadwal;
    private javax.swing.JButton btnLapCeklis;
    private javax.swing.JButton btnLapJadwal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox comboPengawasCeklis;
    private javax.swing.JComboBox comboPengawasJadwal;
    private javax.swing.JComboBox comboPetugasCeklis;
    private javax.swing.JComboBox comboPetugasJadwal;
    private javax.swing.JComboBox comboShift;
    private javax.swing.JComboBox<String> comboStatus;
    private com.toedter.calendar.JDateChooser dateCeklisDari;
    private com.toedter.calendar.JDateChooser dateCeklisSampai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbAllCeklisBln;
    private javax.swing.JRadioButton rbAllCeklisTgl;
    private javax.swing.JRadioButton rbAllJadwal;
    private javax.swing.JRadioButton rbBlnCeklis;
    private javax.swing.JRadioButton rbBlnJadwal;
    private javax.swing.JRadioButton rbTgl;
    private com.toedter.calendar.JYearChooser thnCuserCeklis;
    private com.toedter.calendar.JYearChooser thnCuserJadwal;
    // End of variables declaration//GEN-END:variables
}
